### ISSUE TITLE
Release into ROS Lunar

### ISSUE THREAD

**Issue by 130s** [ros-interactive-manipulation/manipulation_msgs#10]

**Comment by v4hn** [comment]
This package is deprecated and should not be released into lunar in my opinion:

See https://github.com/ros-interactive-manipulation/manipulation_msgs/issues/9 and https://github.com/ros-planning/moveit/commit/29564393260a8d5bac41eb036aedb282149fffa2

**Comment by 130s** [comment]
@v4hn thanks for clarification (and reminder). I think I just took something wrong in [Lunar blocker list](http://repositories.ros.org/status_page/blocked_releases_lunar.html?s=6&r=1). I added a deprecation notice on the top page of this repo and on [wiki](http://wiki.ros.org/action/info/manipulation_msgs?action=diff&rev2=9&rev1=8).
