### ISSUE TITLE
ROS wiki doc not being built

### ISSUE THREAD

**Issue by bit-pirate** [ros-interactive-manipulation/manipulation_msgs#6]
http://www.ros.org/wiki/manipulation_msgs

**Comment by 130s** [comment]
I now see at least package.xml is pulled in from Groovy onward.
If you meant "doc" as in doc entry on rosdistro, it's added from Kinetic https://github.com/ros-interactive-manipulation/manipulation_msgs/issues/7#issuecomment-233944385
