### ISSUE TITLE
Release into kinetic

### ISSUE THREAD

**Issue by davetcoleman** [ros-interactive-manipulation/manipulation_msgs#7]
MoveIt! depends on this package https://github.com/ros-planning/moveit_ros/issues/695

**Comment by davetcoleman** [comment]
ping @tfoote @isucan need help releasing this

**Comment by davetcoleman** [comment]
@130s since you're already doing a great job with releasing moveit debians, think you could release these also?

**Comment by 130s** [comment]
Once the deb of https://github.com/ros-interactive-manipulation/household_objects_database_msgs/issues/3#issuecomment-233791635, one of missing dependencies, becomes available on shadow-fixed, this can be released.

**Comment by 130s** [comment]
Done https://github.com/ros/rosdistro/pull/12204 for Kinetic.

For I, J, I don't think we need another release since it's been released already and there hasn't been any update.

**Comment by davetcoleman** [comment]
thank you @130s !

**Comment by 130s** [comment]
NOTE that MoveIt! moved away from using this package #9
